# Use root/example as user/password credentials
version: '3'

services:
  mongodb_backup:
    image: mongo
    restart: always
    volumes:
      - '/backup'
    command:
      mongodump --uri mongodb://root:example@mongodb:27017/ --archive=/tmp/dump.archive
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/